---
java_url: http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz
java_folder: /opt
java_name: "{{java_folder}}/jdk1.7.0_79"
java_archive: "{{java_folder}}/jdk-7u79-linux-x64.tar.gz"