---

- include: supervisord.yaml

- name: install npm
  yum: name=npm state=installed
  sudo: true

- name: install git
  yum: name=git state=installed
  sudo: true

- name: create hubot user
  user:
    name: hubot
    comment: "beep boop i am a robot"
    state: present
  sudo: true

- name: ensure /var/log/hubot exists
  file:
    path: /var/log/hubot
    state: directory
    mode: 0755
    owner: hubot
  sudo: true

- name: update hubot repo
  git:
    dest: /home/hubot/hubot
    repo: '{{hubot_repo}}'
    update: yes
  sudo: true
  sudo_user: hubot
  notify:
    - restart hubot

- name: install hubot configuration
  template:
    src: local.env.j2
    dest: /home/hubot/hubot/local.env
  sudo: true
  sudo_user: hubot
  notify:
    - restart hubot

- name: install hubot packages
  shell: npm install
  args:
    chdir: /home/hubot/hubot
  sudo: true
  sudo_user: hubot
  notify:
    - restart hubot

- name: install hubot service
  template:
    src: hubot.conf.j2
    dest: /etc/supervisord.conf.d/hubot.conf
  sudo: true
  notify:
    - restart supervisord
    - restart hubot

# force supervisord to load the hubot config
# in case this was a fresh install
# XXX remove
- name: restart supervisord
  service: name=supervisord state=restarted
  sudo: true

- name: ensure hubot is running
  supervisorctl: name=hubot state=started
  sudo: true
  register: hubot_running

  # could be "hubot: started"
  # or       "hubot: ERROR (already started)"
  failed_when: '("started" not in hubot_running.msg)'
