---
- name: install npm
  yum: name=npm state=installed
  sudo: true

- name: install git
  yum: name=git state=installed
  sudo: true

- name: install supervisord
  yum: name=supervisor state=installed
  sudo: true

- name: create hubot user
  user: name=hubot comment="beep boop i am a robot" state=present
  sudo: true

- name: ensure /var/log/hubot exists
  file: path=/var/log/hubot state=directory mode=0755 owner=hubot
  sudo: true

- name: update hubot repo
  git: dest=/home/hubot/hubot repo={{hubot_repo}} update=yes
  sudo: true
  sudo_user: hubot
  notify:
    - restart hubot

- name: install hubot configuration
  template: src=config.sh.j2 dest=/home/hubot/hubot/config.sh
  sudo: true
  sudo_user: hubot
  notify:
    - restart hubot

- name: install hubot packages
  shell: npm install
  args:
    chdir: /home/hubot/hubot
  sudo: true
  sudo_user: hubot
  notify:
    - restart hubot

- name: install hubot service
  template: src=supervisord.conf.j2 dest=/home/hubot/supervisord.conf
  sudo: true
  sudo_user: hubot
  notify:
    - restart supervisord
    - restart hubot    

- name: ensure hubot is running
  supervisorctl: name=hubot state=started config=/home/hubot/supervisord.conf
  sudo: true
  sudo_user: hubot
