---
- name: install npm
  yum: name=npm state=installed
  sudo: true

- name: install git
  yum: name=git state=installed
  sudo: true

- name: update hubot repo
  git: dest=/home/vagrant/hubot repo={{hubot_repo}} update=yes

- name: install hubot configuration
  template: src=config.sh.j2 dest=/home/vagrant/hubot/config.sh

- name: install hubot
  shell: npm install
  args:
    chdir: /home/vagrant/hubot
