---

- name: uninstall supervisord (yum)
  yum: name=supervisor state=absent
  become: true

- name: install pip
  yum: name=python-pip state=installed
  become: true

- name: install python-meld3
  yum: name=python-meld3 state=installed
  become: true

- name: install supervisord (pip)
  pip: name=supervisor state=present version=3.3
  become: true

- name: install supervisord init script
  copy:
    src: supervisord
    dest: /etc/rc.d/init.d/supervisord
    mode: 0755
  become: true

- name: install supervisord config
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf
  become: true
  notify: restart supervisord

- name: create supervisord service dir
  file:
    name: /etc/supervisord.conf.d
    state: directory
    mode: 0755
  become: true

- name: create /var/log/supervisor
  file:
    name: /var/log/supervisor
    state: directory
    mode: 0700
  become: true

- name: ensure supervisord is running and enabled
  service: name=supervisord state=started enabled=yes
  become: true
