---
- name: uninstall supervisord (yum)
  yum:
    name: supervisor
    state: absent

- name: install python-meld3
  yum:
    name: python-meld3
    state: installed

- name: install supervisord (pip)
  pip:
    name: supervisor
    state: present
    version: 3.3

- name: install supervisord init script
  copy:
    src: files/supervisord/supervisord
    dest: /etc/rc.d/init.d/supervisord
    mode: 0755

- name: install supervisord config
  template:
    src: templates/supervisord/supervisord.conf.j2
    dest: /etc/supervisord.conf
  notify: restart supervisord

- name: create supervisord service dir
  file:
    name: /etc/supervisord.conf.d
    state: directory
    mode: 0755

- name: create /var/log/supervisor
  file:
    name: /var/log/supervisor
    state: directory
    mode: 0700

- name: ensure supervisord is running and enabled
  service:
    name: supervisord
    state: started
    enabled: yes
