---
  - name: install git
    yum: name=git-all
    become: yes

  - name: clone api
    git: repo={{ api_repo_url }}
         dest=/home/vagrant/apis/{{ api_dir }}
         accept_hostkey=yes
    become: yes