---
  - name: install pip
    yum:
      name: python-pip
      state: installed
    when: ansible_distribution == 'CentOS'

  - name: install pip
    apt:
      name: python-pip
    when: ansible_distribution == 'Debian'