---
  - name: install EPEL
    yum:
      name: epel-release
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: install pip
    yum:
      name: python-pip
      state: installed
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: install pip
    apt:
      name: python-pip
      update_cache: yes
    when: ansible_distribution == 'Debian'