---
  # Set up user and group

  - name: create group apis
    group:
      name: apis
      state: present

  - name: create user osu_apis
    user:
      name: osu_apis
      comment: "OSU APIs"
      group: apis
      password: "{{ user_psw }}"

  # Create directories

  - name: create apis directory structure
    file:
      path: '{{ item }}'
      state: directory
      group: apis
      owner: osu_apis
      mode: 0770
    with_items:
      - /apis
      - /apis/apis
      - /apis/config
      - /apis/logs
      - /apis/run.d

  - name: create /apis/keytool_files directory
    file:
      path: /apis/keytool_files
      state: directory
      group: apis
      owner: osu_apis
      mode: 0555

  - name: generate / refresh certs
    include: gen-certs.yml

  # Install supervisor

  - name: create /apis/supervisor directory
    file:
      path: /apis/supervisor
      state: directory
      group: apis
      owner: osu_apis
      mode: 0750

  - name: install config file for the api supervisor
    copy:
      src: supervisord.conf
      dest: /apis/supervisor/supervisord.conf
      group: apis
      owner: osu_apis
      mode: 0644

  - name: copy api job template
    copy:
      src: api-service-template.conf
      dest: /apis/run.d/template
      group: apis
      owner: osu_apis
      mode: 0644

  - name: copy scripts
    copy:
      src: '{{ item }}'
      dest: '/apis/{{ item }}'
      group: apis
      owner: osu_apis
      mode: 0754
    with_items:
      - jenkins-run.sh
      - supervisord-run.sh

  - name: create api_supervisor job
    copy:
      src: api_supervisor.conf
      dest: /etc/supervisord.conf.d/api_supervisor.conf
      mode: 0644

  - name: reload api_supervisord job
    supervisorctl:
      name: api_supervisor
      state: present

  - name: ensure the api supervisor is started
    supervisorctl:
      name: api_supervisor
      state: started
