---
  - name: create group apis
    group:
      name: apis
      state: present

  - name: create user osu_apis
    user:
      name: osu_apis
      comment: "OSU APIs"
      group: apis
      password: "{{ user_psw }}"

  - name: create apis directory
    file:
      path: /apis
      state: directory
      group: apis
      owner: osu_apis
      mode: 0770
      recurse: yes

  - name: create apis/keytool_files directory
    file:
      path: /apis/keytool_files
      state: directory
      group: apis
      owner: osu_apis
      mode: 0555
      recurse: yes

  - name: create apis/logs directory
    file:
      path: /apis/logs
      state: directory
      group: apis
      owner: osu_apis
      mode: 0770
      recurse: yes

  - name: clone api
    git:
      repo: "{{ api_repo_url }}"
      dest: /apis/{{ api_dir }}
      accept_hostkey: yes
      version: "{{ api_version }}"

  - name: setup the dir mode and owner
    file:
      path: /apis/{{ api_dir }}
      group: apis
      owner: osu_apis
      mode: 0770
      recurse: yes
